#!/usr/bin/env bash
# Start SIERRA secure gallery on the TAHOE rig
#
# SIERRA Wi-Fi is already provided by the DECO mesh router.
# This script does NOT create a hotspot — it only:
#   1. Detects the TAHOE rig's IP on the SIERRA/LAN network
#   2. Deploys authenticated nginx config (IP-restricted + basic auth)
#   3. Starts/reloads nginx
#   4. Starts dnsmasq so 'tahoe' resolves on the SIERRA network
#
# Usage: sudo bash scripts/sierra-start.sh
#        make sierra-start

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NGINX_BIN="/usr/local/opt/nginx/bin/nginx"
NGINX_CONF="/usr/local/etc/nginx/nginx.conf"
AUTH_FILE="/usr/local/etc/nginx/.sierra-auth"

[[ $EUID -ne 0 ]] && { echo "  ERROR: run with sudo: sudo $0"; exit 1; }

echo ""
echo "  SIERRA — Secure Customer Gallery"
echo "  ─────────────────────────────────────────"
echo "  (SIERRA Wi-Fi is already active via DECO)"
echo ""

# ── 1. Detect TAHOE's bridge IP on the SIERRA hotspot network ─────────────────
echo "  [1/3] Detecting TAHOE bridge IP for SIERRA..."

# Find TAHOE's IP on the SIERRA/DECO network.
# Priority:
#   1. Active Internet Sharing bridge (if hotspot is running — DECO connects here)
#   2. Primary LAN interface (en0 etc — if DECO is independently on the same network)
BRIDGE_IF=""
TAHOE_IP=""

# Try bridge interfaces first (Internet Sharing active)
for br in bridge103 bridge100 bridge101 bridge102; do
  IP=$(ipconfig getifaddr "$br" 2>/dev/null || true)
  if [[ -n "$IP" ]]; then
    BRIDGE_IF="$br"
    TAHOE_IP="$IP"
    break
  fi
done

# Fall back to primary LAN interface (DECO in AP mode on same network)
if [[ -z "$TAHOE_IP" ]]; then
  for iface in en0 en9 en1 en2; do
    IP=$(ipconfig getifaddr "$iface" 2>/dev/null || true)
    if [[ -n "$IP" ]] && ! echo "$IP" | grep -qE "^169\.254|^127\."; then
      BRIDGE_IF="$iface"
      TAHOE_IP="$IP"
      break
    fi
  done
fi

if [[ -z "$TAHOE_IP" ]]; then
  echo "  ERROR: Cannot detect TAHOE IP on any network interface."
  exit 1
fi

SIERRA_SUBNET=$(echo "$TAHOE_IP" | awk -F. '{print $1"."$2"."$3".0/24"}')
SIERRA_DOMAIN="sierra"

echo "     TAHOE bridge : $TAHOE_IP (on $BRIDGE_IF)"
echo "     SIERRA subnet: $SIERRA_SUBNET"
echo "     Domain       : $SIERRA_DOMAIN  (tahoe.sierra, gallery.sierra)"

# ── 2. Deploy nginx config with correct subnet ────────────────────────────────
echo "  [2/3] Deploying authenticated nginx config..."

mkdir -p /usr/local/etc/nginx/servers

# Generate sierra.conf with the actual subnet
cat > /usr/local/etc/nginx/servers/sierra.conf << NGINXEOF
# SIERRA — customer-facing authenticated gallery
# Auto-generated by sierra-start.sh
# TAHOE bridge: $TAHOE_IP ($BRIDGE_IF)  subnet: $SIERRA_SUBNET

server {
    listen       80;
    # Respond to all sierra domain variants + IP direct access
    server_name  tahoe.$SIERRA_DOMAIN
                 gallery.$SIERRA_DOMAIN
                 www.$SIERRA_DOMAIN
                 tahoe tahoe.local
                 $TAHOE_IP;

    # Layer 1: Network isolation — only hotspot/DECO subnet + localhost
    allow $SIERRA_SUBNET;
    allow 127.0.0.1;
    deny  all;

    # Redirect bare root
    location = / {
        return 301 /gallery/;
    }

    # Layer 2: Authenticated gallery
    location /gallery/ {
        auth_basic           "SIERRA — Authorized Access Only";
        auth_basic_user_file $AUTH_FILE;

        alias  $REPO_ROOT/platform/collection/view/;
        index  index.html;
        autoindex off;

        add_header Cache-Control "no-cache, must-revalidate";
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
    }

    # Block everything else
    location / {
        return 403;
    }
}
NGINXEOF

# Copy main nginx.conf
cp "$REPO_ROOT/infra/nginx/nginx.conf" /usr/local/etc/nginx/nginx.conf

# Validate
if "$NGINX_BIN" -t -c "$NGINX_CONF" 2>&1 | grep -v '\[warn\]' | grep -qE '\[error\]|\[emerg\]'; then
  echo "  ERROR: nginx config invalid:"
  "$NGINX_BIN" -t -c "$NGINX_CONF" 2>&1 | sed 's/^/     /'
  exit 1
fi
echo "     Config valid ✓"

# Ensure auth file exists (gallery locked until make add-guest is run)
[[ -f "$AUTH_FILE" ]] || { touch "$AUTH_FILE"; chmod 640 "$AUTH_FILE"; }

# Start or reload nginx
if ps aux | grep -q "[n]ginx: master"; then
  "$NGINX_BIN" -s reload -c "$NGINX_CONF" 2>/dev/null && echo "     nginx reloaded ✓"
else
  "$NGINX_BIN" -c "$NGINX_CONF" 2>/dev/null && echo "     nginx started ✓"
fi

# ── 3. Start dnsmasq so 'tahoe' resolves on SIERRA ───────────────────────────
echo "  [3/3] Starting dnsmasq (tahoe → $TAHOE_IP)..."

mkdir -p /usr/local/etc/dnsmasq.d

# Detect the bridge or interface to listen on
# Listen on all interfaces so SIERRA clients get DNS from this host
cat > /usr/local/etc/dnsmasq.d/sierra.conf << DNSEOF
# dnsmasq — SIERRA domain resolver
# Listens on TAHOE's bridge IP ($TAHOE_IP on $BRIDGE_IF).
# macOS bootpd already tells the DECO to use $TAHOE_IP as DNS.
# The DECO forwards *.sierra queries here; this resolves them.

interface=$BRIDGE_IF
listen-address=$TAHOE_IP,127.0.0.1
bind-interfaces

# Own the 'sierra' TLD — all *.sierra → TAHOE
local=/$SIERRA_DOMAIN/
domain=$SIERRA_DOMAIN

address=/tahoe.$SIERRA_DOMAIN/$TAHOE_IP
address=/gallery.$SIERRA_DOMAIN/$TAHOE_IP
address=/www.$SIERRA_DOMAIN/$TAHOE_IP
address=/tahoe/$TAHOE_IP
address=/tahoe.local/$TAHOE_IP

# Forward everything else upstream
server=8.8.8.8
server=1.1.1.1

log-queries
log-facility=/usr/local/var/log/dnsmasq-sierra.log
DNSEOF

pkill -f "dnsmasq.*sierra" 2>/dev/null || true
sleep 1
/usr/local/sbin/dnsmasq \
  --conf-file=/usr/local/etc/dnsmasq.d/sierra.conf \
  --pid-file=/tmp/dnsmasq-sierra.pid
echo "     dnsmasq running (PID: $(cat /tmp/dnsmasq-sierra.pid 2>/dev/null || echo '?')) ✓"

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════════════════════╗"
echo "  ║  SIERRA gallery is READY on TAHOE                       ║"
echo "  ╠══════════════════════════════════════════════════════════╣"
echo "  ║  TAHOE IP   : $TAHOE_IP"
echo "  ║  Subnet     : $SIERRA_SUBNET (only this can access gallery)"
echo "  ╠══════════════════════════════════════════════════════════╣"
echo "  ║  Customer connects to SIERRA Wi-Fi (via DECO), then:   ║"
echo "  ║    http://tahoe.sierra/gallery/  ← domain (preferred) ║"
echo "  ║    http://gallery.sierra/        ← short alias        ║"
echo "  ║    http://$TAHOE_IP/gallery/   ← IP fallback          ║"
echo "  ╠══════════════════════════════════════════════════════════╣"
echo "  ║  Next:                                                  ║"
echo "  ║    make add-guest NAME=john   create login + QR code   ║"
echo "  ╚══════════════════════════════════════════════════════════╝"
echo ""
